epochs: 10
val_period: 100
batch_size: 2

optimizer:
  name: "sgd"
  lr: 0.00001
  weight_decay: 0

loss: [
#  {
#    name: "tversky_loss",
#    alpha: 0.5,
#    beta: 0.5,
#    weight: 1,
#  },
  {
    name: "negative_ln_dice",
    weight: 0.4
  },
  {
    name: "bce",
    weight: 0.6
  },
#  {
#    name: "soft_jaccard",
#    weight: 0.005
#  },


]

metrics: [
  {
    name: "dice",
    threshold: 0
  },
  {
    name: "jaccard",
    threshold: 0
  },
]


dataset:
  device: ${device}
  debug: False

  train_img_dir: ${storage_path}/${train_img_dir_name}
  train_mask_dir: ${storage_path}/${train_mask_dir_name}
  val_img_dir: ${storage_path}/${val_img_dir_name}
  val_mask_dir: ${storage_path}/${val_mask_dir_name}

  train_proportion: 0.5

  augmentation: [
    {
      name: "color_jitter",
      brightness: 0.1,
      contrast: 0.3,
      saturation: 0.3,
      p: 0.3
    },
    {
      name: "grid_distortion",
      p: 0.3
    },
    {
      name: "elastic_transform",
      p: 0.3
    },
    {
      name: "channel_dropout",
      p: 0.2
    },
#    {
#      name: "coarse_dropout",
#      max_holes: 10,
#      max_width: 5,
#      max_height: 5,
#      fill_value: 255,
#      p: 0.1
#    },
#    {
#      name: "coarse_dropout",
#      max_holes: 10,
#      max_width: 5,
#      max_height: 5,
#      fill_value: 0,
#      p: 0.1
#    },
#    {
#      name: "pixel_dropout",
#      dropout_prob: 0.005,
#      per_channel: False,
#      drop_value: 255,
#      p: 0.1
#    },
#    {
#      name: "pixel_dropout",
#      dropout_prob: 0.005,
#      per_channel: False,
#      drop_value: 0,
#      p: 0.1
#    },
    {
      name: "channel_shuffle",
      p: 0.3
    },
    {
      name: "vertical_flip",
      p: 0.3
    },
    {
      name: "horizontal_flip",
      p: 0.3
    },
#    {
#      name: "random_rotate_90",
#      p: 0.1
#    },
    {
      name: "blur",
      p: 0.1
    },
    {
      name: "to_gray",
      p: 0.1
    },
    {
      name: "rotate",
      always_apply: False,
      p: 0.2
    },
    {
      name: "random_resized_crop",
      height: 330,
      width: 330,
      min_scale: 0.6,
      max_scale: 1,
      always_apply: False,
      p: 0.5
    },
#    {
#      name: normalize,
#      always_apply: True,
#      p: 1
#    },
  ]