epochs: 50
val_period: 10
batch_size: 4

optimizer:
  name: "adam"
  lr: 0.001
  weight_decay: 0

loss: [
  {
    name: "negative_ln_dice",
    weight: 0.2
  },
  {
    name: "bce",
    weight: 0.8
  }
#  {
#    name: "soft_jaccard",
#    weight: 1
#  }
]

metrics: [
  {
    name: "jaccard",
    threshold: 0
  },
]


dataset:
  device: ${device}
  debug: False

  train_img_dir: ${storage_path}/${train_img_dir_name}
  train_mask_dir: ${storage_path}/${train_mask_dir_name}
  val_img_dir: ${storage_path}/${val_img_dir_name}
  val_mask_dir: ${storage_path}/${val_mask_dir_name}

  train_proportion: 0.5

  augmentation: [
    {
      name: "color_jitter",
      brightness: 0.1,
      contrast: 0.3,
      saturation: 0.3,
      p: 0.05
    },
#    {
#      name: "random_crop",
#      height: 256,
#      width: 256,
#      always_apply: True,
#      p: 1
#    },
    {
      name: "random_shadow",
      x_min: 0,
      y_min: 0,
      x_max: 1,
      y_max: 0.4,
      num_shadows_lower: 1,
      num_shadows_upper: 2,
      always_apply: False,
      shadow_dimension: 8,
      p: 0.2
    },
    {
      name: "grid_distortion",
      p: 0.05
    },
    {
      name: "elastic_transform",
      p: 0.05
    },
    {
      name: "channel_dropout",
      p: 0.05
    },
    {
      name: "coarse_dropout",
      max_holes: 5,
      max_width: 5,
      max_height: 5,
      fill_value: 0.984,
      p: 0.1
    },
    {
      name: "coarse_dropout",
      max_holes: 5,
      max_width: 5,
      max_height: 5,
      fill_value: 0,
      p: 0.05
    },
    {
      name: "pixel_dropout",
      dropout_prob: 0.005,
      per_channel: True,
      drop_value: 0.984,
      p: 0.05
    },
    {
      name: "pixel_dropout",
      dropout_prob: 0.005,
      per_channel: True,
      drop_value: 0,
      p: 0.05
    },
    {
      name: "pixel_dropout",
      dropout_prob: 0.005,
      per_channel: True,
      drop_value: 0.5,
      p: 0.05
    },
    {
      name: "channel_shuffle",
      p: 0.05
    },
    {
      name: "vertical_flip",
      p: 0.3
    },
    {
      name: "horizontal_flip",
      p: 0.3
    },
    {
      name: "random_rotate_90",
      p: 0.3
    },
    {
      name: "blur",
      p: 0.05
    },
    {
      name: "to_gray",
      p: 0.05
    }
  ]