epochs: 0
val_period: 10
batch_size: 2

optimizer:
  name: "adam"
  lr: 0.001
  weight_decay: 0

loss: [
  {
    name: "negative_ln_dice",
    weight: 0.4,
  },
  {
    name: "bce",
    weight: 0.6,
  },
]

metrics: [
  {
    name: "dice",
    threshold: 0
  },
  {
    name: "jaccard",
    threshold: 0
  },
]


dataset:
  device: ${device}
  debug: False

  train_img_dir: ${storage_path}/${train_img_dir_name}
  train_mask_dir: ${storage_path}/${train_mask_dir_name}
  val_img_dir: ${storage_path}/${val_img_dir_name}
  val_mask_dir: ${storage_path}/${val_mask_dir_name}

  train_proportion: 0.5

  bgr_augmentation: [

  ]

  augmentation: [
    {
      name: "normalize",
      always_apply: True,
      p: 1
    }
  ]