epochs: 50
val_period: 50
batch_size: 8
optimizer:
  name: adam
  lr: 0.001
  weight_decay: 0
loss:
- name: negative_ln_dice
  weight: 0.2
- name: bce
  weight: 0.8

metrics:
- name: jaccard
  threshold: 0

dataset:
  device: ${device}
  debug: false
  train_img_dir: ${storage_path}/${train_img_dir_name}
  train_mask_dir: ${storage_path}/${train_mask_dir_name}
  val_img_dir: ${storage_path}/${val_img_dir_name}
  val_mask_dir: ${storage_path}/${val_mask_dir_name}
  train_proportion: 0.5
  augmentation:
  - name: color_jitter
    brightness: 0.1
    contrast: 0.3
    saturation: 0.3
    p: 0.1
  - name: random_shadow
    x_min: 0
    y_min: 0.1
    x_max: 1
    y_max: 0.4
    num_shadows_lower: 1
    num_shadows_upper: 2
    always_apply: false
    shadow_dimension: 8
    p: 0.2
  - name: grid_distortion
    p: 0.1
  - name: elastic_transform
    p: 0.1
  - name: channel_dropout
    p: 0.1
  - name: coarse_dropout
    max_holes: 5
    max_width: 5
    max_height: 5
    fill_value: 0.984
    p: 0.1
  - name: coarse_dropout
    max_holes: 5
    max_width: 5
    max_height: 5
    fill_value: 0
    p: 0.1
  - name: pixel_dropout
    dropout_prob: 0.005
    per_channel: true
    drop_value: 0.984
    p: 0.1
  - name: pixel_dropout
    dropout_prob: 0.005
    per_channel: true
    drop_value: 0
    p: 0.1
  - name: pixel_dropout
    dropout_prob: 0.005
    per_channel: true
    drop_value: 0.5
    p: 0.1
  - name: channel_shuffle
    p: 0.2
  - name: vertical_flip
    p: 0.5
  - name: horizontal_flip
    p: 0.5
  - name: blur
    p: 0.2
  - name: to_gray
    p: 0.1
  - name: normalize
    always_apply: True
    p: 1