epochs: 30
val_period: 10
batch_size: 10

optimizer:
  name: "adam"
  lr: 0.001
  weight_decay: 0

loss: [
  {
    name: "negative_ln_dice",
    weight: 0.25
  },
  {
    name: "bce",
    weight: 0.75
  }
]

metrics: [
  {
    name: "dice",
    threshold: 0
  },
  {
    name: "dice",
    threshold: 0.1
  },
  {
    name: "dice",
    threshold: 0.3
  },
  {
    name: "dice",
    threshold: 0.5
  },

]


dataset:
  device: ${device}
  debug: False

  train_img_dir: ${storage_path}/${train_img_dir_name}
  train_mask_dir: ${storage_path}/${train_mask_dir_name}
  val_img_dir: ${storage_path}/${val_img_dir_name}
  val_mask_dir: ${storage_path}/${val_mask_dir_name}

  train_proportion: 0.5

  augmentation: [
    {
      name: "channel_dropout",
      p: 0.5
    },
    {
      name: "coarse_dropout",
      max_holes: 4,
      max_width: 8,
      max_height: 8,
      fill_value: 255
    },
    {
      name: "coarse_dropout",
      max_holes: 10,
      max_width: 6,
      max_height: 6,
      fill_value: 254
    },
    {
      name: "channel_shuffle",
      p: 0.5
    },
    {
      name: "vertical_flip",
      p: 0.5
    },
    {
      name: "horizontal_flip",
      p: 0.5
    },
    {
      name: "blur",
      p: 0.5
    },
    {
      name: "color_jitter",
      brightness: 0.1,
      contrast: 0.5,
      saturation: 0.5,
      p: 0.5
    }
  ]