thresholds: [0]
batch_size: 8

metrics: [
    {
    name: dice,
    threshold: 1.0
    },
    {
    name: dice,
    threshold: 1.02
    },
    {
    name: dice,
    threshold: 1.04
    },
    {
    name: dice,
    threshold: 1.06
    },
    {
    name: dice,
    threshold: 1.08
    },
    {
    name: dice,
    threshold: 1.1
    },
    {
    name: dice,
    threshold: 1.12
    },
    {
    name: dice,
    threshold: 1.14
    },
    {
    name: dice,
    threshold: 1.16
    },
    {
    name: dice,
    threshold: 1.18
    },
    {
    name: dice,
    threshold: 1.2
    },
    {
    name: dice,
    threshold: 1.22
    },
    {
    name: dice,
    threshold: 1.24
    },
    {
    name: dice,
    threshold: 1.26
    },
    {
    name: dice,
    threshold: 1.28
    },
    {
    name: dice,
    threshold: 1.3
    },
    {
    name: dice,
    threshold: 1.32
    },
    {
    name: dice,
    threshold: 1.34
    },
    {
    name: dice,
    threshold: 1.36
    },
    {
    name: dice,
    threshold: 1.38
    },
    {
    name: dice,
    threshold: 1.4
    },
    {
    name: dice,
    threshold: 1.42
    },
    {
    name: dice,
    threshold: 1.44
    },
    {
    name: dice,
    threshold: 1.46
    },
    {
    name: dice,
    threshold: 1.48
    },
    {
    name: dice,
    threshold: 1.5
    },
    {
    name: dice,
    threshold: 1.52
    },
    {
    name: dice,
    threshold: 1.54
    },
    {
    name: dice,
    threshold: 1.56
    },
    {
    name: dice,
    threshold: 1.58
    },
    {
    name: dice,
    threshold: 1.6
    },
    {
    name: dice,
    threshold: 1.62
    },
    {
    name: dice,
    threshold: 1.64
    },
    {
    name: dice,
    threshold: 1.66
    },
    {
    name: dice,
    threshold: 1.68
    },
    {
    name: dice,
    threshold: 1.7
    },
    {
    name: dice,
    threshold: 1.72
    },
    {
    name: dice,
    threshold: 1.74
    },
    {
    name: dice,
    threshold: 1.76
    },
    {
    name: dice,
    threshold: 1.78
    },
    {
    name: dice,
    threshold: 1.8
    },
    {
    name: dice,
    threshold: 1.82
    },
    {
    name: dice,
    threshold: 1.84
    },
    {
    name: dice,
    threshold: 1.86
    },
    {
    name: dice,
    threshold: 1.88
    },
    {
    name: dice,
    threshold: 1.9
    },
    {
    name: dice,
    threshold: 1.92
    },
    {
    name: dice,
    threshold: 1.94
    },
    {
    name: dice,
    threshold: 1.96
    },
    {
    name: dice,
    threshold: 1.98
    },
    {
    name: dice,
    threshold: 2.0
    },
    {
    name: dice,
    threshold: 2.02
    },
    {
    name: dice,
    threshold: 2.04
    },
    {
    name: dice,
    threshold: 2.06
    },
    {
    name: dice,
    threshold: 2.08
    },
    {
    name: dice,
    threshold: 2.1
    },
    {
    name: dice,
    threshold: 2.12
    },
    {
    name: dice,
    threshold: 2.14
    },
    {
    name: dice,
    threshold: 2.16
    },
    {
    name: dice,
    threshold: 2.18
    },
    {
    name: dice,
    threshold: 2.2
    },
    {
    name: dice,
    threshold: 2.22
    },
    {
    name: dice,
    threshold: 2.24
    },
    {
    name: dice,
    threshold: 2.26
    },
    {
    name: dice,
    threshold: 2.28
    },
    {
    name: dice,
    threshold: 2.3
    },
    {
    name: dice,
    threshold: 2.32
    },
    {
    name: dice,
    threshold: 2.34
    },
    {
    name: dice,
    threshold: 2.36
    },
    {
    name: dice,
    threshold: 2.38
    },
    {
    name: dice,
    threshold: 2.4
    },
    {
    name: dice,
    threshold: 2.42
    },
    {
    name: dice,
    threshold: 2.44
    },
    {
    name: dice,
    threshold: 2.46
    },
    {
    name: dice,
    threshold: 2.48
    },
    {
    name: dice,
    threshold: 2.5
    },
    {
    name: dice,
    threshold: 2.52
    },
    {
    name: dice,
    threshold: 2.54
    },
    {
    name: dice,
    threshold: 2.56
    },
    {
    name: dice,
    threshold: 2.58
    },
    {
    name: dice,
    threshold: 2.6
    },
    {
    name: dice,
    threshold: 2.62
    },
    {
    name: dice,
    threshold: 2.64
    },
    {
    name: dice,
    threshold: 2.66
    },
    {
    name: dice,
    threshold: 2.68
    },
    {
    name: dice,
    threshold: 2.7
    },
    {
    name: dice,
    threshold: 2.72
    },
    {
    name: dice,
    threshold: 2.74
    },
    {
    name: dice,
    threshold: 2.76
    },
    {
    name: dice,
    threshold: 2.78
    },
    {
    name: dice,
    threshold: 2.8
    },
    {
    name: dice,
    threshold: 2.82
    },
    {
    name: dice,
    threshold: 2.84
    },
    {
    name: dice,
    threshold: 2.86
    },
    {
    name: dice,
    threshold: 2.88
    },
    {
    name: dice,
    threshold: 2.9
    },
    {
    name: dice,
    threshold: 2.92
    },
    {
    name: dice,
    threshold: 2.94
    },
    {
    name: dice,
    threshold: 2.96
    },
    {
    name: dice,
    threshold: 2.98
    },
    {
    name: dice,
    threshold: 3.0
    },
    {
    name: dice,
    threshold: 3.02
    },
    {
    name: dice,
    threshold: 3.04
    },
    {
    name: dice,
    threshold: 3.06
    },
    {
    name: dice,
    threshold: 3.08
    },
    {
    name: dice,
    threshold: 3.1
    },
    {
    name: dice,
    threshold: 3.12
    },
    {
    name: dice,
    threshold: 3.14
    },
    {
    name: dice,
    threshold: 3.16
    },
    {
    name: dice,
    threshold: 3.18
    },
    {
    name: dice,
    threshold: 3.2
    },
    {
    name: dice,
    threshold: 3.22
    },
    {
    name: dice,
    threshold: 3.24
    },
    {
    name: dice,
    threshold: 3.26
    },
    {
    name: dice,
    threshold: 3.28
    },
    {
    name: dice,
    threshold: 3.3
    },
    {
    name: dice,
    threshold: 3.32
    },
    {
    name: dice,
    threshold: 3.34
    },
    {
    name: dice,
    threshold: 3.36
    },
    {
    name: dice,
    threshold: 3.38
    },
    {
    name: dice,
    threshold: 3.4
    },
    {
    name: dice,
    threshold: 3.42
    },
    {
    name: dice,
    threshold: 3.44
    },
    {
    name: dice,
    threshold: 3.46
    },
    {
    name: dice,
    threshold: 3.48
    },
    {
    name: dice,
    threshold: 3.5
    },
    {
    name: dice,
    threshold: 3.52
    },
    {
    name: dice,
    threshold: 3.54
    },
    {
    name: dice,
    threshold: 3.56
    },
    {
    name: dice,
    threshold: 3.58
    },
    {
    name: dice,
    threshold: 3.6
    },
    {
    name: dice,
    threshold: 3.62
    },
    {
    name: dice,
    threshold: 3.64
    },
    {
    name: dice,
    threshold: 3.66
    },
    {
    name: dice,
    threshold: 3.68
    },
    {
    name: dice,
    threshold: 3.7
    },
    {
    name: dice,
    threshold: 3.72
    },
    {
    name: dice,
    threshold: 3.74
    },
    {
    name: dice,
    threshold: 3.76
    },
    {
    name: dice,
    threshold: 3.78
    },
    {
    name: dice,
    threshold: 3.8
    },
    {
    name: dice,
    threshold: 3.82
    },
    {
    name: dice,
    threshold: 3.84
    },
    {
    name: dice,
    threshold: 3.86
    },
    {
    name: dice,
    threshold: 3.88
    },
    {
    name: dice,
    threshold: 3.9
    },
    {
    name: dice,
    threshold: 3.92
    },
    {
    name: dice,
    threshold: 3.94
    },
    {
    name: dice,
    threshold: 3.96
    },
    {
    name: dice,
    threshold: 3.98
    },
    {
    name: dice,
    threshold: 4.0
    },
    {
    name: dice,
    threshold: 4.02
    },
    {
    name: dice,
    threshold: 4.04
    },
    {
    name: dice,
    threshold: 4.06
    },
    {
    name: dice,
    threshold: 4.08
    },
    {
    name: dice,
    threshold: 4.1
    },
    {
    name: dice,
    threshold: 4.12
    },
    {
    name: dice,
    threshold: 4.14
    },
    {
    name: dice,
    threshold: 4.16
    },
    {
    name: dice,
    threshold: 4.18
    },
    {
    name: dice,
    threshold: 4.2
    },
    {
    name: dice,
    threshold: 4.22
    },
    {
    name: dice,
    threshold: 4.24
    },
    {
    name: dice,
    threshold: 4.26
    },
    {
    name: dice,
    threshold: 4.28
    },
    {
    name: dice,
    threshold: 4.3
    },
    {
    name: dice,
    threshold: 4.32
    },
    {
    name: dice,
    threshold: 4.34
    },
    {
    name: dice,
    threshold: 4.36
    },
    {
    name: dice,
    threshold: 4.38
    },
    {
    name: dice,
    threshold: 4.4
    },
    {
    name: dice,
    threshold: 4.42
    },
    {
    name: dice,
    threshold: 4.44
    },
    {
    name: dice,
    threshold: 4.46
    },
    {
    name: dice,
    threshold: 4.48
    },
    {
    name: dice,
    threshold: 4.5
    },
    {
    name: dice,
    threshold: 4.52
    },
    {
    name: dice,
    threshold: 4.54
    },
    {
    name: dice,
    threshold: 4.56
    },
    {
    name: dice,
    threshold: 4.58
    },
    {
    name: dice,
    threshold: 4.6
    },
    {
    name: dice,
    threshold: 4.62
    },
    {
    name: dice,
    threshold: 4.64
    },
    {
    name: dice,
    threshold: 4.66
    },
    {
    name: dice,
    threshold: 4.68
    },
    {
    name: dice,
    threshold: 4.7
    },
    {
    name: dice,
    threshold: 4.72
    },
    {
    name: dice,
    threshold: 4.74
    },
    {
    name: dice,
    threshold: 4.76
    },
    {
    name: dice,
    threshold: 4.78
    },
    {
    name: dice,
    threshold: 4.8
    },
    {
    name: dice,
    threshold: 4.82
    },
    {
    name: dice,
    threshold: 4.84
    },
    {
    name: dice,
    threshold: 4.86
    },
    {
    name: dice,
    threshold: 4.88
    },
    {
    name: dice,
    threshold: 4.9
    },
    {
    name: dice,
    threshold: 4.92
    },
    {
    name: dice,
    threshold: 4.94
    },
    {
    name: dice,
    threshold: 4.96
    },
    {
    name: dice,
    threshold: 4.98
    },
    {
    name: dice,
    threshold: 5.0
    },
    {
    name: dice,
    threshold: 5.02
    },
    {
    name: dice,
    threshold: 5.04
    },
    {
    name: dice,
    threshold: 5.06
    },
    {
    name: dice,
    threshold: 5.08
    },
    {
    name: dice,
    threshold: 5.1
    },
    {
    name: dice,
    threshold: 5.12
    },
    {
    name: dice,
    threshold: 5.14
    },
    {
    name: dice,
    threshold: 5.16
    },
    {
    name: dice,
    threshold: 5.18
    },
    {
    name: dice,
    threshold: 5.2
    },
    {
    name: dice,
    threshold: 5.22
    },
    {
    name: dice,
    threshold: 5.24
    },
    {
    name: dice,
    threshold: 5.26
    },
    {
    name: dice,
    threshold: 5.28
    },
    {
    name: dice,
    threshold: 5.3
    },
    {
    name: dice,
    threshold: 5.32
    },
    {
    name: dice,
    threshold: 5.34
    },
    {
    name: dice,
    threshold: 5.36
    },
    {
    name: dice,
    threshold: 5.38
    },
    {
    name: dice,
    threshold: 5.4
    },
    {
    name: dice,
    threshold: 5.42
    },
    {
    name: dice,
    threshold: 5.44
    },
    {
    name: dice,
    threshold: 5.46
    },
    {
    name: dice,
    threshold: 5.48
    },
    {
    name: dice,
    threshold: 5.5
    },
    {
    name: dice,
    threshold: 5.52
    },
    {
    name: dice,
    threshold: 5.54
    },
    {
    name: dice,
    threshold: 5.56
    },
    {
    name: dice,
    threshold: 5.58
    },
    {
    name: dice,
    threshold: 5.6
    },
    {
    name: dice,
    threshold: 5.62
    },
    {
    name: dice,
    threshold: 5.64
    },
    {
    name: dice,
    threshold: 5.66
    },
    {
    name: dice,
    threshold: 5.68
    },
    {
    name: dice,
    threshold: 5.7
    },
    {
    name: dice,
    threshold: 5.72
    },
    {
    name: dice,
    threshold: 5.74
    },
    {
    name: dice,
    threshold: 5.76
    },
    {
    name: dice,
    threshold: 5.78
    },
    {
    name: dice,
    threshold: 5.8
    },
    {
    name: dice,
    threshold: 5.82
    },
    {
    name: dice,
    threshold: 5.84
    },
    {
    name: dice,
    threshold: 5.86
    },
    {
    name: dice,
    threshold: 5.88
    },
    {
    name: dice,
    threshold: 5.9
    },
    {
    name: dice,
    threshold: 5.92
    },
    {
    name: dice,
    threshold: 5.94
    },
    {
    name: dice,
    threshold: 5.96
    },
    {
    name: dice,
    threshold: 5.98
    }
]
