thresholds: [0, 0.5]
batch_size: 8

metrics: [
    {
        name: dice,
        threshold: 0
    },
    {
        name: dice,
        threshold: 0.1
    },
    {
        name: dice,
        threshold: 0.12
    },
    {
        name: dice,
        threshold: 0.14
    },
    {
        name: dice,
        threshold: 0.16
    },
    {
        name: dice,
        threshold: 0.18
    },
    {
        name: dice,
        threshold: 0.2
    },
    {
        name: dice,
        threshold: 0.22
    },
    {
        name: dice,
        threshold: 0.24
    },
    {
        name: dice,
        threshold: 0.26
    },
    {
        name: dice,
        threshold: 0.28
    },
    {
        name: dice,
        threshold: 0.3
    },
    {
        name: dice,
        threshold: 0.32
    },
    {
        name: dice,
        threshold: 0.34
    },
    {
        name: dice,
        threshold: 0.36
    },
    {
        name: dice,
        threshold: 0.38
    },
    {
        name: dice,
        threshold: 0.4
    },
    {
        name: dice,
        threshold: 0.42
    },
    {
        name: dice,
        threshold: 0.44
    },
    {
        name: dice,
        threshold: 0.46
    },
    {
        name: dice,
        threshold: 0.48
    },
    {
        name: dice,
        threshold: 0.5
    },
    {
        name: dice,
        threshold: 0.52
    },
    {
        name: dice,
        threshold: 0.54
    },
    {
        name: dice,
        threshold: 0.56
    },
    {
        name: dice,
        threshold: 0.58
    },

]
