comment: "Attempt"

device: cuda:0

defaults:
  - _self_
  - train_cfg: tmp
#  - train_cfg: u2net_train

  - test_cfg: tmp

#  - model_cfg: resnet101_unet
#  - model_cfg: cru
#  - model_cfg: ruf
#  - model_cfg: mini_u2net
#  - model_cfg: u2net
  - model_cfg: resnet_u2net
#  - model_cfg: resnet_u2net3

#  - dataset_cfg: tmp
  - dataset_cfg:  bgr_color
#  - dataset_cfg: strong_aug

