storage_path: ${hydra:runtime.cwd}/../data

train_img_dir_name: imgs
train_mask_dir_name: segmented_imgs
val_img_dir_name: imgs
val_mask_dir_name: segmented_imgs

device: "cuda:0"

load_pretrained: True
pretrained_path: outputs/2023-03-05/20-17-58

defaults:
  - _self_
  - model_conf: tmp
  - test_conf: tmp
  - train_conf: tmp

