epochs: 100
val_period: 2
batch_size: 4

# minimizing loss that is a weighted sum
loss: [
    {
        name: u2net_neg_ln_dice,
        weight: 0.1
    },
    {
        name: u2net_inv_neg_ln_dice,
        weight: 0.1
    },
    {
        name: u2net_bce,
        weight: 0.8
    },
    {
        name: u2net_soft_jaccard,
        weight: 0.005
    },
    {
        name: u2net_inv_soft_jaccard,
        weight: 0.005
    }
]

# metrics computed during the validation
metrics: [
  "soft_dice",
  "soft_jaccard"
]

optimizer:
    name: "adam"
    lrs: [0.001]
    weight_decays: [0]


# changes lrs depending on mean loss (mean of means per batch) of validation
scheduler:
    name: "reduce_on_plateau"
    factor: 0.1
#    step_size: 10

# stops depending on target metric that have to be in metrics
early_stopper:
    save_path: ${hydra:runtime.output_dir}
    target_metric: "soft_jaccard"
    statistic: "mean"
    patience: 10
    delta: 0

